
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Thu Apr 11 20:33:15 CEST 2013
//----------------------------------------------------

package testCup;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int DIVIDE = 5;
  public static final int MULT = 4;
  public static final int EOF = 0;
  public static final int PLUS = 2;
  public static final int ENTIER = 9;
  public static final int error = 1;
  public static final int PAR_G = 6;
  public static final int MOINS = 3;
  public static final int PAR_D = 7;
  public static final int POINT_VIRGULE = 8;
}

